config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :articles do
    resources :comments
  end
  resources :users, only: [:new, :create]

  namespace :api do
    namespace :v1 do
      resources :articles, only: [:index, :show]
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }

  def preview
    if text.length <= 25
      # Return if the text is already sufficiently short
      text
    else
      # Ensure length will be <= 25 even after '...' is appended
      truncated = text[0..22]

      # Remove characters until a space is found (so we don't break a word)
      while truncated[truncated.length - 1] != ' ' && truncated.length > 0
        truncated = truncated[0..truncated.length - 2]
      end

      # Remove the space
      truncated = truncated[0..truncated.length - 2] if truncated[truncated.length - 1] == ' '

      # Append '...' and return
      truncated + '...'
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  has_many :comments

  validates :email, uniqueness: true

  has_secure_password
end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < ApplicationController
  def index
    render json: Article.all
  end

  def show
    render json: Article.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_login, except: [:index, :show]
  before_action :require_article_owner, only: [:edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end
   
  def create
    @article = Article.new(article_params)
   
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
   
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
   
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text).merge(user: User.find(session[:user_id]))
  end

  def require_login
    redirect_to login_path unless session[:user_id]
  end

  def require_article_owner
    user = User.find(session[:user_id])
    article = Article.find(params[:id])
    redirect_to root_path, alert: 'You may not access that article.' unless article.user == user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login
  before_action :require_comment_owner, only: [:destroy]

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private

  def comment_params
    params.require(:comment).permit(:commenter, :body).merge(user: User.find(session[:user_id]))
  end

  def require_login
    redirect_to login_path unless session[:user_id]
  end

  def require_comment_owner
    user = User.find(session[:user_id])
    comment = Comment.find(params[:id])
    redirect_to root_path, alert: 'You may not access that comment.' unless comment.user == user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, alert: 'Logged in!'
    else
      redirect_to login_path, alert: 'Invalid credentials; please try again'
    end
  end

  def destroy
    session[:user_id] = nil

    redirect_to root_path, alert: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
   
  def create
    @user = User.new(user_params)
   
    if @user.save
      redirect_to root_path, notice: 'Registered! Please log in.'
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    session[:user_id].present?
  end

  def current_user
    if logged_in?
      User.find(session[:user_id])
    end
  end
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td>
        <% if article.user == current_user %>
          <%= link_to 'Edit', edit_article_path(article) %>
        <% end %>
      </td>
      <td>
        <% if article.user == current_user %>
          <%= link_to 'Destroy', article_path(article),
                      method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 
<h2>Comments</h2>
<%= render @article.comments %>
 
<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<% if @article.user == current_user %> 
  <%= link_to 'Edit Article', edit_article_path(@article) %> |
<% end %>
<%= link_to 'Back to Articles', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<p>
  <% if comment.user == current_user %>
    <%= link_to 'Destroy Comment', [comment.article, comment],
                 method: :delete,
                 data: { confirm: 'Are you sure?' } %>
  <% end %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice] %>
  <p>
    <%= flash[:notice] %>
  </p>
<% end %>
<% if flash[:alert] %>
  <p>
    <%= flash[:alert] %>
  </p>
<% end %>

<% if logged_in? %>
  <%= link_to 'Sign Out', logout_path %>
<% else %>
  <%= link_to 'Sign In', login_path %>
<% end %>

<hr>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited
      this user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>
 
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>